version: '3.8'

services:
  couriertracking-app:
    image: couriertracking:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:mem:couriertracking
      SPRING_DATASOURCE_DRIVER_CLASSNAME: org.h2.driver
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.H2Dialect
    depends_on:
      - couriertracking-db